version: "3"
services:
  clamav:
    container_name: clamav
    image: mkodockx/docker-clamav
    hostname: clamav
    restart: always 
    logging:
      driver: awslogs
      options: 
        awslogs-group: /aws/ecs/av-scanner-service
        awslogs-region: us-east-1
        awslogs-stream-prefix: clam_server     
  app:
    image: app:latest
    container_name: clamav-scan-api
    restart: always
    build: .
    ports:
      - "0:3000"
    links:
      - clamav
    environment:
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
    links:
      - clamav
    depends_on:
      - clamav
    logging:
      driver: awslogs
      options: 
        awslogs-group: /aws/ecs/av-scanner-service
        awslogs-region: us-east-1
        awslogs-stream-prefix: clam_api  
