version: "3"
services:
  clamav:
    container_name: clamav
    image: mkodockx/docker-clamav
    hostname: clamav
    restart: always
    ports:
      - "3310:3310"    
  app:
    image: app:latest
    container_name: clamav-scan-api
    restart: always
    build: .
    ports:
      - "0:3000"
    links:
      - clamav
    environment:
      - CLAMAV_HOST=clamav
      - CLAMAV_PORT=3310
    links:
      - clamav
    depends_on:
      - clamav
