version: 2
defaults: &defaults
    docker:
      - image: circleci/python:stretch-browsers
install_dependency: &install_dependency
          name: Installation of build and deployment dependencies.
          command: |
            sudo apt install jq
            sudo pip3 install awscli --upgrade
            sudo pip3 install docker-compose
install_deploysuite: &install_deploysuite
          name: Installation of install_deploysuite.
          command: |
            git clone --branch v1.4.1 https://github.com/topcoder-platform/tc-deploy-scripts ../buildscript
            cp ./../buildscript/master_deploy.sh .
            cp ./../buildscript/buildenv.sh .
            cp ./../buildscript/awsconfiguration.sh .
run_build: &run_build
          name: Installation of build dependencies.
          command: ./build.sh
jobs:
  # Build & Deploy against development backend
  "build-dev":
    <<: *defaults
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - run: *run_build
      - deploy:
          name: Running deployment.
          command: |
            ./awsconfiguration.sh DEV
            source awsenvconf
            ./buildenv.sh -e DEV -b dev-global-appvar,dev-av-scanner-service-buildvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e DEV -t latest -s dev-global-appvar,dev-av-scanner-service-appvar -i av-scanner-service
  "build-prod":
    <<: *defaults
    steps:
      # Initialization.
      - checkout
      - setup_remote_docker
      - run: *install_dependency
      - run: *install_deploysuite
      - run: *run_build
      - deploy:
          name: Running MasterScript.
          command: |
            ./awsconfiguration.sh PROD
            source awsenvconf
            ./buildenv.sh -e PROD -b prod-global-appvar,prod-av-scanner-service-buildvar
            source buildenvvar
            ./master_deploy.sh -d ECS -e PROD -t latest -s prod-global-appvar,prod-av-scanner-service-appvar -i av-scanner-service
workflows:
  version: 2
  build:
    jobs:
      # Development builds are executed on "develop" branch only.
      - "build-dev":
          context : org-global
          filters:
            branches:
              only:
                - develop
      - "build-prod":
          context : org-global
          filters:
            branches:
              only: master 
